// Package pg contains generated code for schema 'public'.
package pg

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"

	"gitlab.com/distributed_lab/kit/pgdb"
	"gitlab.com/distributed_lab/logan/v3/errors"
	"gitlab.com/rarimo/relayer-svc/internal/data"
)

// Storage is the helper struct for database operations
type Storage struct {
	db *pgdb.DB
}

// New - returns new instance of storage
func New(db *pgdb.DB) *Storage {
	return &Storage{
		db,
	}
}

// DB - returns db used by Storage
func (s *Storage) DB() *pgdb.DB {
	return s.db
}

// Clone - returns new storage with clone of db
func (s *Storage) Clone() *Storage {
	return New(s.db.Clone())
}

// Transaction begins a transaction on repo.
func (s *Storage) Transaction(tx func() error) error {
	return s.db.Transaction(tx)
} // GorpMigrationQ represents helper struct to access row of 'gorp_migrations'.
type GorpMigrationQ struct {
	db *pgdb.DB
}

// NewGorpMigrationQ  - creates new instance
func NewGorpMigrationQ(db *pgdb.DB) *GorpMigrationQ {
	return &GorpMigrationQ{
		db,
	}
}

// GorpMigrationQ  - creates new instance of GorpMigrationQ
func (s Storage) GorpMigrationQ() *GorpMigrationQ {
	return NewGorpMigrationQ(s.DB())
}

var colsGorpMigration = `id, applied_at`

// InsertCtx inserts a GorpMigration to the database.
func (q GorpMigrationQ) InsertCtx(ctx context.Context, gm *data.GorpMigration) error {
	// sql insert query, primary key must be provided
	sqlstr := `INSERT INTO public.gorp_migrations (` +
		`id, applied_at` +
		`) VALUES (` +
		`$1, $2` +
		`)`
	// run
	err := q.db.ExecRawContext(ctx, sqlstr, gm.ID, gm.AppliedAt)
	return errors.Wrap(err, "failed to execute insert query")
}

// Insert insert a GorpMigration to the database.
func (q GorpMigrationQ) Insert(gm *data.GorpMigration) error {
	return q.InsertCtx(context.Background(), gm)
}

// UpdateCtx updates a GorpMigration in the database.
func (q GorpMigrationQ) UpdateCtx(ctx context.Context, gm *data.GorpMigration) error {
	// update with composite primary key
	sqlstr := `UPDATE public.gorp_migrations SET ` +
		`applied_at = $1 ` +
		`WHERE id = $2`
	// run
	err := q.db.ExecRawContext(ctx, sqlstr, gm.AppliedAt, gm.ID)
	return errors.Wrap(err, "failed to execute update")
}

// Update updates a GorpMigration in the database.
func (q GorpMigrationQ) Update(gm *data.GorpMigration) error {
	return q.UpdateCtx(context.Background(), gm)
}

// UpsertCtx performs an upsert for GorpMigration.
func (q GorpMigrationQ) UpsertCtx(ctx context.Context, gm *data.GorpMigration) error {
	// upsert
	sqlstr := `INSERT INTO public.gorp_migrations (` +
		`id, applied_at` +
		`) VALUES (` +
		`$1, $2` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`applied_at = EXCLUDED.applied_at `
	// run
	if err := q.db.ExecRawContext(ctx, sqlstr, gm.ID, gm.AppliedAt); err != nil {
		return errors.Wrap(err, "failed to execute upsert stmt")
	}
	return nil
}

// Upsert performs an upsert for GorpMigration.
func (q GorpMigrationQ) Upsert(gm *data.GorpMigration) error {
	return q.UpsertCtx(context.Background(), gm)
}

// DeleteCtx deletes the GorpMigration from the database.
func (q GorpMigrationQ) DeleteCtx(ctx context.Context, gm *data.GorpMigration) error {
	// delete with single primary key
	sqlstr := `DELETE FROM public.gorp_migrations ` +
		`WHERE id = $1`
	// run
	if err := q.db.ExecRawContext(ctx, sqlstr, gm.ID); err != nil {
		return errors.Wrap(err, "failed to exec delete stmt")
	}
	return nil
}

// Delete deletes the GorpMigration from the database.
func (q GorpMigrationQ) Delete(gm *data.GorpMigration) error {
	return q.DeleteCtx(context.Background(), gm)
} // StateQ represents helper struct to access row of 'states'.
type StateQ struct {
	db *pgdb.DB
}

// NewStateQ  - creates new instance
func NewStateQ(db *pgdb.DB) *StateQ {
	return &StateQ{
		db,
	}
}

// StateQ  - creates new instance of StateQ
func (s Storage) StateQ() *StateQ {
	return NewStateQ(s.DB())
}

var colsState = `id, operation, confirmation`

// InsertCtx inserts a State to the database.
func (q StateQ) InsertCtx(ctx context.Context, s *data.State) error {
	// sql insert query, primary key must be provided
	sqlstr := `INSERT INTO public.states (` +
		`id, operation, confirmation` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)`
	// run
	err := q.db.ExecRawContext(ctx, sqlstr, s.ID, s.Operation, s.Confirmation)
	return errors.Wrap(err, "failed to execute insert query")
}

// Insert insert a State to the database.
func (q StateQ) Insert(s *data.State) error {
	return q.InsertCtx(context.Background(), s)
}

// UpdateCtx updates a State in the database.
func (q StateQ) UpdateCtx(ctx context.Context, s *data.State) error {
	// update with composite primary key
	sqlstr := `UPDATE public.states SET ` +
		`operation = $1, confirmation = $2 ` +
		`WHERE id = $3`
	// run
	err := q.db.ExecRawContext(ctx, sqlstr, s.Operation, s.Confirmation, s.ID)
	return errors.Wrap(err, "failed to execute update")
}

// Update updates a State in the database.
func (q StateQ) Update(s *data.State) error {
	return q.UpdateCtx(context.Background(), s)
}

// UpsertCtx performs an upsert for State.
func (q StateQ) UpsertCtx(ctx context.Context, s *data.State) error {
	// upsert
	sqlstr := `INSERT INTO public.states (` +
		`id, operation, confirmation` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`operation = EXCLUDED.operation, confirmation = EXCLUDED.confirmation `
	// run
	if err := q.db.ExecRawContext(ctx, sqlstr, s.ID, s.Operation, s.Confirmation); err != nil {
		return errors.Wrap(err, "failed to execute upsert stmt")
	}
	return nil
}

// Upsert performs an upsert for State.
func (q StateQ) Upsert(s *data.State) error {
	return q.UpsertCtx(context.Background(), s)
}

// DeleteCtx deletes the State from the database.
func (q StateQ) DeleteCtx(ctx context.Context, s *data.State) error {
	// delete with single primary key
	sqlstr := `DELETE FROM public.states ` +
		`WHERE id = $1`
	// run
	if err := q.db.ExecRawContext(ctx, sqlstr, s.ID); err != nil {
		return errors.Wrap(err, "failed to exec delete stmt")
	}
	return nil
}

// Delete deletes the State from the database.
func (q StateQ) Delete(s *data.State) error {
	return q.DeleteCtx(context.Background(), s)
}

// GorpMigrationByIDCtx retrieves a row from 'public.gorp_migrations' as a GorpMigration.
//
// Generated from index 'gorp_migrations_pkey'.
func (q GorpMigrationQ) GorpMigrationByIDCtx(ctx context.Context, id string, isForUpdate bool) (*data.GorpMigration, error) {
	// query
	sqlstr := `SELECT ` +
		`id, applied_at ` +
		`FROM public.gorp_migrations ` +
		`WHERE id = $1`
	// run
	if isForUpdate {
		sqlstr += " for update"
	}
	var res data.GorpMigration
	err := q.db.GetRawContext(ctx, &res, sqlstr, id)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, nil
		}

		return nil, errors.Wrap(err, "failed to exec select")
	}

	return &res, nil
}

// GorpMigrationByID retrieves a row from 'public.gorp_migrations' as a GorpMigration.
//
// Generated from index 'gorp_migrations_pkey'.
func (q GorpMigrationQ) GorpMigrationByID(id string, isForUpdate bool) (*data.GorpMigration, error) {
	return q.GorpMigrationByIDCtx(context.Background(), id, isForUpdate)
}

// StateByOperationCtx retrieves a row from 'public.states' as a State.
//
// Generated from index 'states_operation_key'.
func (q StateQ) StateByOperationCtx(ctx context.Context, operation string, isForUpdate bool) (*data.State, error) {
	// query
	sqlstr := `SELECT ` +
		`id, operation, confirmation ` +
		`FROM public.states ` +
		`WHERE operation = $1`
	// run
	if isForUpdate {
		sqlstr += " for update"
	}
	var res data.State
	err := q.db.GetRawContext(ctx, &res, sqlstr, operation)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, nil
		}

		return nil, errors.Wrap(err, "failed to exec select")
	}

	return &res, nil
}

// StateByOperation retrieves a row from 'public.states' as a State.
//
// Generated from index 'states_operation_key'.
func (q StateQ) StateByOperation(operation string, isForUpdate bool) (*data.State, error) {
	return q.StateByOperationCtx(context.Background(), operation, isForUpdate)
}

// StateByIDCtx retrieves a row from 'public.states' as a State.
//
// Generated from index 'states_pkey'.
func (q StateQ) StateByIDCtx(ctx context.Context, id string, isForUpdate bool) (*data.State, error) {
	// query
	sqlstr := `SELECT ` +
		`id, operation, confirmation ` +
		`FROM public.states ` +
		`WHERE id = $1`
	// run
	if isForUpdate {
		sqlstr += " for update"
	}
	var res data.State
	err := q.db.GetRawContext(ctx, &res, sqlstr, id)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, nil
		}

		return nil, errors.Wrap(err, "failed to exec select")
	}

	return &res, nil
}

// StateByID retrieves a row from 'public.states' as a State.
//
// Generated from index 'states_pkey'.
func (q StateQ) StateByID(id string, isForUpdate bool) (*data.State, error) {
	return q.StateByIDCtx(context.Background(), id, isForUpdate)
}
